addind new pool agent

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,4 +1,3 @@
-# azure-pipelines.yml
 trigger:
   - main
 
@@ -14,21 +13,20 @@ stages:
       - job: BuildApp
         displayName: 'Build Java Application'
         pool:
-          vmImage: 'ubuntu-latest'
+          name: 'windows'  # Updated agent pool name
         steps:
-          - script: |
-              ls -la
-              echo "Checking if pom.xml exists:"
-              if [ -f "pom.xml" ]; then echo "pom.xml found"; else echo "pom.xml NOT found"; fi
-              echo "Maven version:"
-              mvn --version
-              echo "Starting Maven build with debug:"
-              mvn -X clean package
-            displayName: 'Build with Maven (Debug Mode)'
+          - task: Maven@3
+            displayName: 'Build Java Application'
+            inputs:
+              mavenPomFile: 'pom.xml'
+              goals: 'package'
+              publishJUnitResults: true
+              testResultsFiles: '**/surefire-reports/TEST-*.xml'
+              javaHomeOption: 'JDKVersion'
+              jdkVersionOption: '11'
 
           - task: CopyFiles@2
             displayName: 'Copy JAR to staging directory'
-            condition: succeeded()
             inputs:
               SourceFolder: '$(System.DefaultWorkingDirectory)/target'
               Contents: '*.jar'
@@ -36,7 +34,6 @@ stages:
 
           - task: PublishBuildArtifacts@1
             displayName: 'Publish JAR Artifact'
-            condition: succeeded()
             inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)'
               ArtifactName: 'java-app'
@@ -50,27 +47,37 @@ stages:
       - job: DeployToK8s
         displayName: 'Deploy to Kubernetes Cluster'
         pool:
-          vmImage: 'ubuntu-latest'
-        variables:
-          - group: KubernetesConfig
+          name: 'windows'  # Updated agent pool name
         steps:
+          - task: DownloadBuildArtifacts@1
+            inputs:
+              buildType: 'current'
+              downloadType: 'single'
+              artifactName: 'java-app'
+              downloadPath: '$(System.ArtifactsDirectory)'
+
           - script: |
-              # Decode base64 kubeconfig
-              echo "$(kubeconfig_base64)" | base64 -d > kubeconfig.yaml
-              chmod 600 kubeconfig.yaml
-              
-              # Use kubeconfig
-              export KUBECONFIG=$(pwd)/kubeconfig.yaml
-              
-              # Test connection
-              kubectl get namespaces
-              
-              # Deploy with Helm
-              helm upgrade --install $(releaseName) $(helmChartPath) \
-                --namespace $(namespace) \
-                --set image.repository=nginx \
-                --set image.tag=latest \
-                --set ingress.hostname=$(releaseName).$(namespace).dev.oclc.org \
-                -f $(helmChartPath)/values/dev.yaml \
-                --wait --timeout 5m
-            displayName: 'Deploy with Helm using decoded kubeconfig'
+              curl -k https://rancher-m1.dev.oclc.org/k8s/clusters/c-m-p8n7sgzn/version || echo "K8s API connectivity failed"
+            displayName: 'Test K8s API Connectivity'
+
+          - task: HelmDeploy@0
+            displayName: 'Deploy Helm Chart'
+            inputs:
+              connectionType: 'Kubernetes Service Connection'
+              kubernetesServiceConnection: 'Cluster_Connection'
+              namespace: '$(namespace)'
+              command: 'upgrade'
+              chartType: 'FilePath'
+              chartPath: '$(helmChartPath)'
+              releaseName: '$(releaseName)'
+              valueFile: '$(helmChartPath)/values/dev.yaml'
+              overrideValues: |
+                image.repository=nginx
+                image.tag=latest
+                ingress.hostname=$(releaseName).$(namespace).dev.oclc.org
+              waitForExecution: true
+              arguments: '--timeout 5m'
+
+          - script: |
+              echo "Application deployed to: https://$(releaseName).$(namespace).dev.oclc.org"
+            displayName: 'Print Deployment Info'
